### ISSUE TITLE
Verify that HttpResponse.[allocate, prepend, ensureCapacity] works as intended

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#69] opened 2010-10-18 21:06 UTC

**Comment by schildmeijer** [comment] 2010-10-19 16:41
Implemented #65 (Optimize ByteBuffer usage in critial write path) and #69 (Verify that HttpResponse.[allocate, prepend, ensureCapacity] works as intended) (closed by f5486845cd17c76563f1a8a385b275c6ce162edf closed by f5486845cd17c76563f1a8a385b275c6ce162edf)

**Closed as completed by schildmeijer** 2010-10-19 16:41 UTC
Labels: core, 0.2.0
