### ISSUE TITLE
Timeout for asynchronous http requests

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#23] opened 2010-09-23 16:13 UTC
30s?

should probably be checked in the I/O loop.

**Comment by rschildmeijer** [comment] 2010-10-05 21:31
the proposal above is incorrect. no timeouts for async http req.

**Comment by schildmeijer** [comment] 2010-10-05 21:43
Typo. #23 (Timeout for asynchronous http requests) work as intended. Closed by 84a6ce594494ff92c90e142f58bed1ba9e322633

**Closed as completed by schildmeijer** 2010-10-05 21:43 UTC
Labels: core, 0.1.0
