### ISSUE TITLE
Optimize ByteBuffer usage in critial write path

### ISSUE THREAD

**Issue by rschildmeijer** [rschildmeijer/deft#65] opened 2010-10-16 13:12 UTC
#63 (Asynchronous write) introduced alot of ByteBuffer usage. Optimize this usage.

Hint: (ByteBuffer usage in) HttpResponse.[write, flush, finish, ensureCapacity, allocate, prepend]

BB reuse (e.g single bb used for both read and write), key methods: flip() // prepare bb for writing
when write is done, if buffer has remaining => compact() // make room for more data be read in

**Comment by rschildmeijer** [comment] 2010-10-17 18:10
Pre study: http://bit.ly/bzWWCS (contains more than bb usage. e.g. questioning the explicit "data staging" (maybe SelectionKey attachment is simplier/better))

**Comment by rschildmeijer** [comment] 2010-10-18 17:29
Tried using a single (public static final ByteByffer readBuffer) and run hello world benchmark (-k -c25 -n800000) no diff.

**Comment by rschildmeijer** [comment] 2010-10-18 18:30
Tried using a single readBuffer for each SelectionKey (i.e removed the stagedData map).
No diff

**Comment by schildmeijer** [comment] 2010-10-19 16:41
Implemented #65 (Optimize ByteBuffer usage in critial write path) and #69 (Verify that HttpResponse.[allocate, prepend, ensureCapacity] works as intended) (closed by f5486845cd17c76563f1a8a385b275c6ce162edf closed by f5486845cd17c76563f1a8a385b275c6ce162edf)

**Closed as completed by schildmeijer** 2010-10-19 16:41 UTC
Labels: core, 0.2.0
